import {StyleSheet} from 'react-native';
import Colors from '../../utils/color';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.white,
    position: 'relative',
    paddingBottom: '30%',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 20,
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  title: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: '400',
  },
  secondaryTitle: {
    fontSize: 20,
    color: Colors.black,
    fontWeight: '500',
    letterSpacing: 1,
  },
  removeTitle: {
    fontSize: 20,
    color: Colors.tertiary,
    fontWeight: '500',
    letterSpacing: 1,
  },
  checkoutContainer: {
    position: 'absolute',
    bottom: 10,
    height: '8%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkoutButton: {
    width: '86%',
    height: '90%',
    backgroundColor: Colors.primary,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkoutButtonText: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 1,
    color: Colors.white,
    textTransform: 'uppercase',
  },
  productContainer: {
    width: '100%',
    height: 100,
    marginVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageContainer: {
    width: '30%',
    height: 100,
    padding: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F0F0F3',
    borderRadius: 10,
    marginRight: 22,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  productInfo: {
    flex: 1,
    height: '100%',
    justifyContent: 'space-around',
  },
  productTitle: {
    fontSize: 14,
    maxWidth: '100%',
    color: '#000000',
    fontWeight: '600',
    letterSpacing: 1,
  },
  priceContainer: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    opacity: 0.6,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: '400',
    maxWidth: '85%',
    marginRight: 4,
  },
  productButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  numberOfProducts: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  minusButton: {
    borderRadius: 100,
    marginRight: 20,
    padding: 4,
    borderWidth: 1,
    borderColor: Colors.qtyIcon,
    opacity: 0.5,
  },
  isOne: {
    borderRadius: 100,
    marginRight: 20,
    padding: 4,
    borderWidth: 1,
    borderColor: '#999999',
    opacity: 0.5,
  },
  materialIcon: {
    fontSize: 16,
    color: '#777777',
  },
  plusButton: {
    borderRadius: 100,
    marginLeft: 20,
    padding: 4,
    borderWidth: 1,
    borderColor: Colors.qtyIcon,
    opacity: 0.5,
  },
  deleteIcon: {
    fontSize: 16,
    color: Colors.white,
    backgroundColor: Colors.tertiary,
    padding: 8,
    borderRadius: 100,
  },
});

export default styles;
