export const ADD_CART = 'ADD_CART';

export const SET_APP = 'SET_APP';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const REQUEST_LOGIN_USER_WITH_FB = 'REQUEST_LOGIN_USER_WITH_FB';
export const REQUEST_CREATE_USER_WITH_FB = 'REQUEST_CREATE_USER_WITH_FB';
export const REQUEST_LOGOUT_USER_WITH_FB = 'REQUEST_LOGOUT_USER_WITH_FB';
export const REQUEST_LOGIN_ERROR = 'REQUEST_LOGIN_ERROR';

export const REQUEST_GET_ALL_PRODUCTS = 'REQUEST_GET_ALL_PRODUCTS';
export const REQUEST_GET_PRODUCT_WITH_ID = 'REQUEST_GET_PRODUCT_WITH_ID';

export const REQUEST_ADD_PRODUCT_FB = 'REQUEST_ADD_PRODUCT_FB';
export const REQUEST_UPDATE_PRODUCT_FB = 'REQUEST_UPDATE_PRODUCT_FB';
export const REQUEST_REMOVE_PRODUCT_FB = 'REQUEST_REMOVE_PRODUCT_FB,';
export const REQUEST_GET_PRODUCTS_FB = 'REQUEST_GET_PRODUCTS_FB';
export const FIREBASE_PRODUCTS_LISTENER = 'FIREBASE_PRODUCTS_LISTENER';

export const REQUEST_ADD_FAVORITE_FB = 'REQUEST_ADD_FAVORITE_FB';
export const REQUEST_REMOVE_FAVORITE_FB = 'REQUEST_REMOVE_FAVORITE_FB,';
export const REQUEST_GET_FAVORITES_FB = 'REQUEST_GET_FAVORITES_FB';
export const FIREBASE_FAVORITES_LISTENER = 'FIREBASE_FAVORITES_LISTENER';
export const SET_LISTENER = 'SET_LISTENER';
